language: ruby
rvm:
  - 2.1
sudo:
  false
install:
  - gem install jekyll
  - gem install html-proofer
script:
  - jekyll build
  - htmlproofer ./_site --only-4xx --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
notifications:
  email:
    on_success: change
    on_failure: always
